### ISSUE TITLE
How do you do to configure a shortcut to use the pa?

### ISSUE THREAD

**Issue by leoheck** [biox/pa#1]
> so, let's define my unique tooling requirements.
getting passwords:
> - i refuse to wait more than a few seconds for most common day-to-day operations.
> - i refuse to type a huge long error-prone password
> - therefore, the secret should be a *key* that i lug around, that can easily be rotated
> - i want passwords to be loaded into my clipboard, pasted wherever my focus is, and then
my clipboard should clear instantly so i don't wind up pasting the password somewhere else
> - the hotkey should be control+shift+p, and should react instantly (within 100ms) when pressed.
> - i should type to filter passwords from a list, then press enter to select the one i like
> - the hotkey should *not* press for me.

Pretty nice tool, dude. Your requirements are pretty much the same as mine and you should consider to put it in the README.md too.

So one thing that I could not find, is how do you do to configure the shortcut thing in Linux, for instance?

**Comment by biox** [comment]
Thank you for the kind words! The answer depends on the desktop environment / window manager you're using. I use i3/sway for everything.

In sway, for example, you can bind a key as follows:

```
bindsym $mod+Shift+p exec --no-startup-id pa-rofi
```

This way, when I press `super+shift+p`, pa-rofi is executed which allows me to select a password. You could do this via a custom Gnome keyboard shortcut if you use Gnome as your desktop manager.

You would need to put pa-rofi in your $PATH somewhere, and also be sure that rofi is installed. Let me know if you have any questions!

**Comment by leoheck** [comment]
Thanks. Yeah, sure, I am on Gnome I will try to set up this. 

How do you use this on Android or in OSX for instance? Do you have any special setup in those places too to make your life easier?

**Comment by biox** [comment]
I don't use a password manager on my phone currently - I normally have a laptop around that I can use if I really need to. In the future I'm going to try and develop a workflow for my Librem 5, but that's still sort of a pipe dream for now.

OSX would be pretty easy, you'd have to build an Alfred workflow or similar I suppose.
