### ISSUE TITLE
Automatic git commits?

### ISSUE THREAD

**Issue by ivanbrennan** [biox/pa#14]
Thanks for this wonderful utility. Are there plans to implement automatic git commit when a password is added/updated/removed?

The [blogpost](https://j3s.sh/thought/storing-passwords-with-age.html) mentioned:
> - `pa add <name-of-password>` shall make a new password, and randomly generate it
>    - if the name is already taken, exit 1
>    - automatically git commits & pushes on exit 0

I'm not so sure about automatic pushes, but automatic commits (like we see in passage and pass) would be great.

**Comment by biox** [comment]
i've been using an alias to do this, but i've felt like this should be baked in for awhile. when i get some free time i'm still interested in an implementation. i'm not quite sure what i want it to look like tho - as unobtrusive as possible ideally.

**Comment by biox** [comment]
i probably will never have the time/energy to do this, but i am open to PRs adding this behavior, as long as the implementation only depends on git & doesn't increase the complexity of `pa` very much.
