### ISSUE TITLE
Multiline passwords

### ISSUE THREAD

**Issue by ghost** [biox/pa#16]
Is there any command to add multiline passwords? "cat > tmp | pa add test" throws the error "stty: stdin isn't a terminal".

**Comment by biox** [comment]
could you just use `pa edit <password>` and paste it?

**Comment by arcxio** [comment]
> could you just use `pa edit <password>` and paste it?

it may be useful to allow `pa edit name` if `name` doesn't exist to create a new entry, wdyt?
