### ISSUE TITLE
`contrib` scripts duplicate code

### ISSUE THREAD

**Issue by apprehensions** [biox/pa#38]
dmenu, fuzzel, rofi, wmenu, and dmenu all share the same code. It is absolutely pointless to have all of the scripts be the same exact code, with the only diffrence being a binary name and arguments. They should all be merged into `pa-dmenu`, since all of the mentioned menu programs behave (and some are the same) as `dmenu`.

Other menu programs can be added in much easier, and maintaining these scripts become easier.

I would be willing to make a PR, however i use my own personal fork of pash and my own password menu script, being able to select properties of an entry.

**Comment by arcxio** [comment]
this has been discussed, see https://github.com/biox/pa/pull/19#issuecomment-2166968000

> from my perspective, the scripts in `contrib/` are meant to be standalone - i'll absolutely accept your shellcheck/pa-wmenu contributions, but abstracting these into a single pa-menu script is too much - lots of folks just copy & paste the thing most relevant to them and the pa-menu abstraction complicates that a little too much for my liking. sorry!!

**Comment by apprehensions** [comment]
Lame.
