### ISSUE TITLE
Where is Installation Section?

### ISSUE THREAD

**Issue by uuc110** [biox/pa#8]
I was looking at your Repo and Readme section and i want to know how to install this please let me know 

I tired adding this in My env variable PATH and it's doing this
![image](https://user-images.githubusercontent.com/44457947/210047511-58a7b582-949f-4440-ad39-833acef29fd0.png)

**Comment by biox** [comment]
you appear to be trying to use `pa` on windows. `pa` will not work on windows - it's meant for *nix style systems.

to install it, just put the shell script anywhere in your $PATH
